const data = 
[
    {
        id:1,
        carName: 'Hyundai Grand i10',
        seatingCapacity: 5,
        description: '1 Large suitcase, 1 Small suitcase',
        imageUrl: './images/1.jpg',
        model:2010,
        color:'black',
        fuel: 'pertol',
        rented:false,
        engine:'81 bhp @ 6000 RPM 1197 cc',
        price: 350,
        vehicleNumber: 'ABC123',
    },
    {
        id:2,
        carName: 'Ford EcoSport',
        seatingCapacity: 4,
        description: 'Ford EcoSport price starts at Rs.8.04 lakh (Ex-Showroom, Delhi) and the top end variant Ford EcoSport Sports Diesel is priced at Rs. 11.67 lakh (Ex-Showroom, Delhi). It is powered by BS6-compliant 1.5-litre petrol and diesel engines.',
        imageUrl: './images/2.jpg',
        model:2010,
        color:'red',
        fuel: 'Diesel',
        rented:false,
        engine:'1.2 Kappa Dual VTVT BS6 Petrol Engine',
        price: 299,
        vehicleNumber: 'ABC456',
    },{
        id:3,
        carName: 'Maruti Suzuki ',
        seatingCapacity: 4,
        description: 'Maruti Suzuki India Limited, formerly known as Maruti Udyog Limited, is an automobile manufacturer in India. It is a 56.21% owned subsidiary of the Japanese car and motorcycle manufacturer Suzuki Motor Corporation. As of July 2018, it had a market share of 53% of the Indian passenger car market.',
        imageUrl: './images/3.jpg',
        model:2010,
        color:'gray',
        fuel: 'petrol',
        rented:true,
        engine:'1.2 Kappa Dual VTVT BS6 Petrol Engine',
        price: 299,
        vehicleNumber: 'ABC123',
    },{
        id:4,
        carName: 'Honda CR-V ',
        seatingCapacity: 4,
        description: 'The Honda CR-V is a compact crossover SUV manufactured by Japanese automaker Honda since 1995 and introduced in the North American market in 1997. ... The CR-V is Honda mid-range utility vehicle, slotting between the smaller Honda HR-V and the larger Honda Passport',
        imageUrl: './images/4.jpg',
        model:2010,
        color:'silver',
        engine:'1.2 Kappa Dual VTVT BS6 Petrol Engine',
        fuel: 'petrol',
        rented:false,
        price: 299,
        vehicleNumber: 'ABC12355',
    },{
        id:5,
        carName: 'Toyota Camry',
        seatingCapacity: 4,
        description: 'Toyota Camry 2019 price starts at Rs.37.88 lakh (Ex-Showroom, Delhi). In its latest avatar, the Camry is powered by a 2.5-litre petrol motor that’s paired with a 88kW motor. The petrol engine makes 178PS of power and 221Nm of torque.',
        imageUrl: './images/5.jpg',
        model:2010,
        color:'brown',
        fuel: '2487 cc',
        rented:false,
        engine:'2487 cc',
        price: 299,
        vehicleNumber: 'ABC123',
    }
];

export default {data};